---
title: Isral Duke, Designer
timezone: UTC
collections:
  awards:
    title: Awards
    output: false
  educations:
    title: Educations
    output: false
  employers:
    title: Employers
    output: false
  posts:
    title: Posts
    output: true
  skills:
    title: Skills
    output: false
  uploads:
    title: Uploads
    output: true
defaults:
- scope:
    path: _posts
    type: posts
  values:
    permalink: articles/:title
    layout: post
    htmlClass: background-light
author: GitHub User
email: isralduke@gmail.com
description: 'Isral Duke is a UX, UI, and Graphic Designer who can also code frontend
  designs.

'
baseurl: ''
url: https://isralduke.com
show_excerpts: false
minima:
  date_format: "%b %-d, %Y"
  social_links:
    twitter: isralduke
    github: isralduke
    linkedin: isralduke
theme: minima
plugins:
- jekyll-feed
- jekyll-seo-tag
- jekyll-paginate
paginate: 5
paginate_path: "/articles/page:num/"
